In [1]:
import numpy as np

In [2]:
arr_1=np.arange(0,11)

In [3]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr_1[4]

4

In [5]:
arr_1[4:2]

array([], dtype=int32)

In [6]:
arr_1[4:8]

array([4, 5, 6, 7])

In [7]:
arr_1[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr_1[6:]

array([ 6,  7,  8,  9, 10])

In [9]:
arr_1[-1]

10

In [10]:
arr_2=arr_1[:4]

In [11]:
arr_2

array([0, 1, 2, 3])

In [12]:
arr_2[:]=99

In [13]:
arr_2

array([99, 99, 99, 99])

In [14]:
arr_1

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr_3=arr_1.copy()

In [16]:
arr_3

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr_3[0:3]=100
arr_3

array([100, 100, 100,  99,   4,   5,   6,   7,   8,   9,  10])

In [19]:
arr_1

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])