In [4]:
import numpy as np

In [5]:
arr_2d_1=np.array([[40,41,43],[53,52,51],[30,35,39]])

In [6]:
arr_2d_1

array([[40, 41, 43],
       [53, 52, 51],
       [30, 35, 39]])

In [4]:
arr_2d_1[0]

array([40, 41, 43])

In [5]:
arr_2d_1[1]

array([53, 52, 51])

In [6]:
arr_2d_1[2]

array([30, 35, 39])

In [7]:
arr_2d_1[0][2]

43

In [8]:
arr_2d_1[2][0]

30

In [9]:
arr_2d_1[2][4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [10]:
arr_2d_1[2,0]

30

In [11]:
arr_2d_1[2,2]

39

In [12]:
arr_2d_1

array([[40, 41, 43],
       [53, 52, 51],
       [30, 35, 39]])

In [15]:
arr_2d_1[1:]

array([[53, 52, 51],
       [30, 35, 39]])

In [17]:
arr_2d_1[1:,1:]

array([[52, 51],
       [35, 39]])

In [9]:
arr_2d_1[1:]

array([[53, 52, 51],
       [30, 35, 39]])

In [10]:
arr_2d_1[1:,1:]

array([[52, 51],
       [35, 39]])

In [11]:
arr_2d_1

array([[40, 41, 43],
       [53, 52, 51],
       [30, 35, 39]])

In [12]:
arr_1d_1=np.arange(1,11)

In [13]:
arr_1d_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_1d_bool=arr_1d_1>3


In [15]:
arr_1d_bool


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
arr_1d_1[arr_1d_bool]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
arr_1d_1[arr_1d_1>5]

array([ 6,  7,  8,  9, 10])

In [18]:
ar_2d_2=np.arange(1,51).reshape(5,10)

In [19]:
ar_2d_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
ar_2d_2[:,5:]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30],
       [36, 37, 38, 39, 40],
       [46, 47, 48, 49, 50]])

In [24]:
ar_2d_2[3:,:2]

array([[31, 32],
       [41, 42]])

In [25]:
ar_2d_2[2:4,3:6]

array([[24, 25, 26],
       [34, 35, 36]])