In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr1 = np.arange(2,21)
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [7]:
arr[0]

0

In [8]:
arr[6]

6

In [9]:
arr[3:5]

array([3, 4])

In [10]:
array[3:]

NameError: name 'array' is not defined

In [11]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [13]:
arr3 = np.arange(2,11)
arr3

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr31=arr3[2:7]

In [15]:
arr31


array([4, 5, 6, 7, 8])

In [16]:
arr31[:]

array([4, 5, 6, 7, 8])

In [17]:
arr31[:] = 100

In [18]:
arr31 ## This is reference of arr3.. not the copy... if anything changed on arr31 will be reflected in arr3

array([100, 100, 100, 100, 100])

In [19]:
arr3

array([  2,   3, 100, 100, 100, 100, 100,   9,  10])

In [20]:
arr32=arr3.copy()  ##Craete another arrey which is exactly copy of arr3

In [21]:
arr32

array([  2,   3, 100, 100, 100, 100, 100,   9,  10])

In [22]:
arr32[:] = 300

In [23]:
arr32 ## This will not change the orignal arry which it is copied


array([300, 300, 300, 300, 300, 300, 300, 300, 300])

In [24]:
arr3

array([  2,   3, 100, 100, 100, 100, 100,   9,  10])