In [1]:
import numpy as np

In [7]:
## Case list into array
list_1=[1,2,3,4,5]
arr_1=np.array(list_1)

In [8]:
print(arr_1)

[1 2 3 4 5]


In [4]:
arr_1

array([1, 2, 3, 4, 5])

In [9]:
## Nested arrey into 2 dimentional array
list_2=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
list_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
three_d_arr=np.array(list_2)
three_d_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
### Create array with rane of number
np.arange(0,11) ## Create 1D array starting 0 to 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
## create 1D array from the range of number to showup only m by muliptly  3
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
## One dimentional array with all zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
## two dimetional array with zeros
np.zeros((3,3))  ## 3 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
## 2 dimentional array with only ones
np.ones((3,5)) ## 3 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0,1,10) ## create a 1D from 0 to 1. each value is equal values by 10

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
## reate indenity matrix
np.eye(3) ## it will create indentity matrix with 3X3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(5) ## it will create 2D with 5X5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
## Create a 1D array with random number
np.random.rand(5) ##1D array with 5 random number

array([0.40044687, 0.19683824, 0.55269875, 0.47418112, 0.51441437])

In [27]:
np.random.rand(5,3) ##2D array with 5 rows and 3 columns

array([[0.59735083, 0.47327857, 0.54277433],
       [0.5777828 , 0.26342067, 0.65137716],
       [0.78497057, 0.23699267, 0.25484835],
       [0.64709455, 0.84707611, 0.72554647],
       [0.87662988, 0.47724423, 0.58680619]])

In [28]:
## create 2D with random negative and prositive number
np.random.randn(4,2)

array([[ 0.12785833, -1.46534166],
       [ 0.13638444, -0.43444339],
       [ 0.85355936, -0.39220664],
       [ 0.20657887, -0.12169955]])

In [30]:
## 1D array with random integer
np.random.randint(10,200) ## get one random integer values between 10 to 200

58

In [31]:
## Get 5 random numbers between 10 to 200
np.random.randint(0,200,5)

array([121,  25,  87, 153,  48])

In [32]:
## Convert 1D into 2D
arr_3=np.arange(25) ##1D array

In [33]:
print(arr_3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [34]:
arr_3.reshape(2,3)

ValueError: cannot reshape array of size 25 into shape (2,3)

In [35]:
arr_3.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr_3


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr_3.max()

24

In [39]:
arr_3.min()

0

In [40]:
## Index location of max value
arr_3.argmax()

24

In [41]:
## Index location of min value
arr_3.argmin()

0

In [43]:
arr_3.shape ## size of array which is 1D array

(25,)

In [44]:
## datatype of array
arr_3.dtype


dtype('int32')

In [45]:
## Get the randint from numpy random
from numpy.random import randint
randint(2,10)

2