In [1]:
import numpy as np

In [2]:
arr_1d_1=np.arange(1,11)

In [3]:
arr_1d_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr_2d_1 = np.arange(1,10).reshape(3,3)

In [6]:
arr_2d_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
ar_1d_add=arr_1d_1+arr_1d_1

In [8]:
ar_1d_add

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr_1d_1 - arr_1d_1


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr_1d_1 * arr_1d_1

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
arr_1d_1 / arr_1d_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
## scalr opertion
arr_1d_1+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [13]:
arr_1d_1 - 200

array([-199, -198, -197, -196, -195, -194, -193, -192, -191, -190])

In [14]:
arr_1d_1 * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
arr_1d_1 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [16]:
arr_1d_1 ** 3


array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [17]:
np.sqrt(arr_1d_1)  ## SQRT of array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [18]:
np.exp(arr_1d_1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [19]:
np.max(arr_1d_1)

10